version: '3.8'
services:
  postgres:
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    image: 'postgres:15.5'
    ports:
      - ${PG_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 1s
      timeout: 10s
      retries: 60
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  migrator:
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    image: 'ghcr.io/amacneil/dbmate:2.12'
    command: -u "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:${PG_PORT}/${POSTGRES_DB}?sslmode=disable" up
    volumes:
      - ./migrations:/db/migrations
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    build: .
    environment:
      - DEBUG_MODE=false
      - SERVER_HOST=0.0.0.0
    ports:
      - ${SERVER_PORT}:8080
    stop_signal: SIGINT
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"