name: Проверка
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8
  tests:
    name: Rest Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.4.2
        pip install numpy
    - name: Make .env file
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_SERVER_PORT: ${{ secrets.SERVER_PORT }}
        envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        envkey_PG_PORT: ${{ secrets.PG_PORT }}
        envkey_SERVER_HOST: ${{ secrets.POSTGRES_HOST }}
    - name: Start docker container
      run: |
        docker compose up -d --build
    - name: Pytest
      run: pytest test_rest.py
    - name: Stop docker container
      run: |
        docker compose down
