name: Проверка
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8
  tests:
    name: Rest Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.4.2
        pip install numpy
    - name: Start docker container
      run: |
        export PG_PORT=${{ secrets.PG_PORT }}
        export SERVER_PORT=${{ secrets.SERVER_PORT }}
        export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
        export SERVER_HOST=${{ secrets.SERVER_HOST }}
        docker compose up
    - name: Pytest
      run: pytest test_rest.py
    - name: Stop docker container
      run: |
        docker compose down
